version: '2'

services:
  ssh-mitm:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    - SSH_MITM_ARGS=--remote-host openssh-server
    ports:
      - "22:10022"

  openssh-server:
    image: hackinglab/alpine-openssh-server
    environment:
    - AUTHOR=e1
    - HL_USER_USERNAME=hacker
    - HL_USER_PASSWORD=compass

