version: '2'

services:
  ssh-mitm:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    - AUTHOR=e1
    - HL_USER_USERNAME=hacker
    - HL_USER_PASSWORD=compass
    - SSH_MITM_ARGS=--remote-host 192.168.0.1
    ports:
      - "10022:10022"
